---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: blog
  name: blog
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - image: "rasooll/blog:latest"
        env:
        - name: url
          value: http://blog-rasooll.apps.ir-thr-at1.arvan.run       
        imagePullPolicy: IfNotPresent
        name: blog
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: '15m'
            ephemeral-storage: 10M
            memory: 50M
          requests:
            cpu: '10m'
            ephemeral-storage: 10M
            memory: 25M
    dnsPolicy: ClusterFirst
    restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blog
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blog
  labels:
    app: blog-route
  annotations:
spec:
  host: blog-rasooll.apps.ir-thr-at1.arvan.run
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: blog-service
    weight: 100
  wildcardPolicy: None