name: CI
on:
  push:
    tags:
    - v**

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.5.1
    - name: Install bundle
      run: gem i bundler -v 1.17.3
    - name: Install dependencies
      run: bundle install --path vendor/bundle
    - name: Run tests
      run: bundle exec jekyll build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builded
        path: ./_site
  docker-build:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: builded
        path: ./_site
    - name: Docker build and push
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        VERSION=${GITHUB_REF##*/}
        docker build . --file Dockerfile --tag rasooll/my-blog:$VERSION
        docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        docker tag rasooll/my-blog:$VERSION rasooll/my-blog:latest
        docker push rasooll/my-blog:$VERSION
        docker push rasooll/my-blog:latest
  kubernetes-deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/blog blog=rasooll/my-blog:${GITHUB_REF##*/}
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment/blog"'
  rsync-deploy:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: builded
        path: ./_site
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzr --delete
        path: ./_site/
        remote_path: /var/www/rasooll.com/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_KEY }}
